name: merge gitlab

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      sha:
        description: "commit sha of latest commit"
        value: ${{ jobs.sync.outputs.sha }}
jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.amog.outputs.sha }}
    steps:
    - uses: actions/checkout@v4

    - name: git config
      run: |
        git config --global user.name "oscam-emu"
        git config --global user.email "oscam-emu@users.noreply.github.com"

    - id: amog
      name: auto-merge oscam-gitlab
      run: |
        git fetch --unshallow
        if git merge --no-ff origin/oscam-gitlab -m "Auto-Merge branch 'oscam-gitlab'"; then
            git push --follow-tags origin
        else
            printf "\nfiles with merge conficts:\n"
            git diff --check
        fi
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
