name: build oscam

on:
  push:
    branches:
      master
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
  workflow_call:
    inputs:
      sha:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.sha }}
        fetch-depth: 0
        
    - name: build libdvbcsa
      run: |
        git clone https://github.com/oe-mirrors/libdvbcsa.git
        cd libdvbcsa
        ./bootstrap
        ./configure --enable-avx2
        make
        sudo make install

    - name: build oscam-emu
      run: |
        ./config.sh --enable all --disable WITH_SOFTCAM
        make
