name: sync gitlab

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: oscam-gitlab

    - name: git config
      run: |
        git config --global user.name "oscam-emu"
        git config --global user.email "oscam-emu@users.noreply.github.com"

    - name: sync oscam-gitlab
      run: |
        git fetch --unshallow
        git remote add --track master streamboard https://git.streamboard.tv/common/oscam.git
        git fetch streamboard
        ahead=$(git rev-list streamboard/master..HEAD --count)
        [ $ahead -gt 0 ] && git reset --hard HEAD~$ahead
        git merge streamboard/master
        git push --follow-tags origin --force

  merge:
    uses: ./.github/workflows/auto-merge.yml
    needs:
      - sync

  build:
    uses: ./.github/workflows/build.yml
    needs:
      - merge
    with:
      sha: ${{ needs.merge.outputs.sha }}

  patch:
    uses: ./.github/workflows/create-patch.yml
    secrets: inherit
    needs:
      - merge
    with:
      sha: ${{ needs.merge.outputs.sha }}
